export const SERVICES = [
  "Home Care", 
  "Supported Housing",
  "  - Supported Living",
  "  - Supported Accommodation",
  "Nursing Homes", 
  "Mental Health Support Services", 
  "Day Services and Community Support", 
  "Live-in Care", 
  "Specialist Clinical Services", 
  "Outreach and Floating Support", 
  "Palliative and End-of-Life Care", 
  "Substance Misuse Support", 
  "Reablement Services", 
  "Short Breaks and Respite Care", 
  "Advocacy and Independent Living Support", 
  "Community Nursing", 
  "Early Help and Family Support Services",
  "Child Contact Centre"
];
